---
title: "AED"
author: "Jose Francisco Domenech Gomis, Eva Barrero Sánchez y Francesc Ruiz Rius"
date: "19/2/2021"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r}
library(readr)
library(tidyr)
library(dplyr)
library(lubridate)
```


```{r}
dfMAPAConsumo <- read_delim("data/Dataset1.- DatosConsumoAlimentarioMAPAporCCAA.txt", "|", escape_double = FALSE, trim_ws = TRUE)
head(dfMAPAConsumo)
```


```{r}
dfPreciosAndalucia <- read_delim("data/Dataset2.- Precios Semanales Observatorio de Precios Junta de Andalucia.txt", "|", escape_double = FALSE, trim_ws = TRUE)
head(dfPreciosAndalucia)
```

```{r}
dfMercaMadrid <- read_delim("data/Dataset3a_Datos_MercaMadrid.txt", "|", escape_double = FALSE, trim_ws = TRUE)
head(dfMercaMadrid)
```

```{r}
dfMercaBarna <- read_delim("data/Dataset3b_Datos_MercaBarna.txt", "|", escape_double = FALSE, trim_ws = TRUE)
head(dfMercaBarna)
```

```{r}
dfComercioExterior <- read_delim("data/Dataset4.- Comercio Exterior de Espana.txt", "|", escape_double = FALSE, col_types = cols(Value = col_character()), 
    trim_ws = TRUE, na=":")
dfComercioExterior<-pivot_wider(data=dfComercioExterior,names_from=c("INDICATORS","FLOW"),values_from=c("Value"),values_fn = list)
head(dfComercioExterior)
```
El dataset 4 daba problemas porque las filas cuyo producto era "Fresh or dried citrus fruit (excl. oranges, lemons..." estaban mal codificadas y tenian una columna de más, esto se ha corregido previamente con un editor de texto.



```{r}
dfCovid <- read_delim("data/Dataset5_Coronavirus_cases.txt", "|", escape_double = FALSE, trim_ws = TRUE) %>% select(-day, -month, -year)
dfCovid$dateRep <- dmy(dfCovid$dateRep)
head(dfCovid)
```


Mapa de España, para utilizarlo más adelante.

```{r}
library(tidyr)
library(rgdal)
library(raster)
library(broom)
library(ggplot2)
```


```{r}
shapefile_provincias <- readOGR("assets/Provincias_ETRS89_30N.shp")
```

```{r}
data_provincias <- tidy(shapefile_provincias)
nombres_provincias <- tibble(shapefile_provincias$Texto) %>% 
  mutate(id = as.character(seq(0, nrow(.)-1)))

data_provincias_mapa <- data_provincias %>% 
  left_join(nombres_provincias, by = "id")
```

```{r}
data_provincias_mapa %>%
  ggplot() +
  geom_polygon(aes( x= long, y = lat, group = group),
               fill = "steelblue", alpha = 0.8, size = 0.05, col = 'tomato') +
  theme_void() + 
  ggtitle("Mapa de España separado por provincias")
```