---
title: "Shiny App"
author: "Jose Francisco Domenech Gomis, Eva Barrero Sánchez y Francesc Ruiz Rius"
date: "13/3/2021"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r}
library(shiny)
library(shinythemes)
library(ggplot2)
library(dplyr)
```

```{r}
ui<-navbarPage(theme = shinytheme("flatly"),
               "Dashboard datacultores", 
  tabPanel("Selección de mákina", 
           sidebarLayout(
             sidebarPanel(
                h5("MÁQUINA")),
                mainPanel(h5("Aquí mostraremos las variables A´s"))
             )),
  navbarMenu("Estado de la mákina",
             tabPanel("Evolución temporal alarmas",
                      sidebarLayout(
                        sidebarPanel(
                          h5("ALARMAS radiobuttons")),
                          mainPanel(h5("Aquí mostraremos las variables A´s en un gráfico"))
                        )
                      ),
             tabPanel("Registros de la máquina",
                      sidebarLayout(
                        sidebarPanel(
                          h5("ALARMAS checkbox")),
                          mainPanel(h5("Aquí mostraremos una tabla con los eventos de la máquina seleccionada"))
                        )
                      )),
  tabPanel("Estadísticas Globales Temporales",
             sidebarLayout(
             sidebarPanel(
                h5("PERIODO Y ESTADÍSTICAS")),
                mainPanel(h5("Aquí mostraremos determinados estadísticos en un periodo temporal"))
             ))
)

server <- function(input, output) { }

shinyApp(ui, server)
```



